import type { Metadata } from "next";
import "../globals.css";
import { Layout } from "../ui/layout";
import { IUser } from "../lib/definition";
import { auth } from "@/auth";
import { logout } from "../lib/action";

export const metadata: Metadata = {
  title: "BConfig",
  description: "Generated by bsoft",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return <Layout user={session?.user! as IUser}>{children}</Layout>;
}
