import type { Metadata } from "next";
import "../globals.css";
import { Layout } from "../ui/layout";

export const metadata: Metadata = {
  title: "BConfig",
  description: "Generated by bsoft",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <Layout>{children}</Layout>;
}
