import type { Metadata } from "next";
import "../globals.css";
import { Layout } from "../ui/layout";
import { IUser } from "../lib/definition";
import { auth } from "@/auth";
import HolyLoader from "holy-loader";

export const metadata: Metadata = {
  title: "BConfig",
  description: "Generated by bsoft",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <>
      <Layout user={session?.user! as IUser}>
        <HolyLoader
          color="linear-gradient(to right, #f1f522, #1e61fc, #a855f7)"
          speed={250}
          easing="linear"
          showSpinner
        />
        {children}
      </Layout>
    </>
  );
}
